// Public, disposable test-only key. Never use this certificate outside tests.
export const importTlsKey = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgqu4BeTY4ABpdq3/L
Ar+GXWkiU2GZl2Z4bvvx5M8TbEGhRANCAAQPUkHfrghGdvBwhJHMeUy7HZrMV0MI
f2syEpvnDBmJVPmYDLWbOXu2wx74kZb0ssP7Zze5K5A2oLfYxclXuplm
-----END PRIVATE KEY-----`;

export const importTlsCertificate = `-----BEGIN CERTIFICATE-----
MIIBoTCCAUigAwIBAgIUEHVFrCCMGZlwZEPQMYEm7wkNHdAwCgYIKoZIzj0EAwIw
GTEXMBUGA1UEAwwOcHVibGljLmV4YW1wbGUwHhcNMjYxMDAzMDM0MzI5WhcNMzYw
OTMwMDM0MzI5WjAZMRcwFQYDVQQDDA5wdWJsaWMuZXhhbXBsZTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABA9SQd+uCEZ28HCEkcx5TLsdmsxXQwh/azISm+cMGYlU
+ZgMtZs5e7bDHviRlvSyw/tnN7krkDagt9jFyVe6mWajbjBsMB0GA1UdDgQWBBQS
Zy09eWRsOu5AoGtyJTExrks+AzAfBgNVHSMEGDAWgBQSZy09eWRsOu5AoGtyJTEx
rks+AzAPBgNVHRMBAf8EBTADAQH/MBkGA1UdEQQSMBCCDnB1YmxpYy5leGFtcGxl
MAoGCCqGSM49BAMCA0cAMEQCIBPXFuVT8jxJVTl5PZehCWcvC3jzxVqXvSDZI6O0
muT+AiB2DllBR4FmMa9Mp9w5l6hlZbHYG2QySKEynQUURa5ung==
-----END CERTIFICATE-----`;
